import { Patient } from "@/types/patient";

export const patients: Patient[] = [
  {
    id: "1",
    uhid: "AX240001",
    name: "Rahul Sharma",
    age: 54,
    gender: "Male",
    patientType: "IPD",
    ward: "ICU",
    bed: "ICU-03",
    consultant: "Dr. Patil",
    diagnosis: "Pneumonia",
    status: "Critical",
    updated: "5 min ago",
  },
  {
    id: "2",
    uhid: "AX240002",
    name: "Priya Desai",
    age: 38,
    gender: "Female",
    patientType: "IPD",
    ward: "Ward B",
    bed: "B-214",
    consultant: "Dr. Shah",
    diagnosis: "Dengue",
    status: "Stable",
    updated: "12 min ago",
  },
  {
    id: "3",
    uhid: "AX240003",
    name: "Amit Kulkarni",
    age: 61,
    gender: "Male",
    patientType: "OPD",
    ward: "-",
    bed: "-",
    consultant: "Dr. Joshi",
    diagnosis: "Diabetes",
    status: "Consultation",
    updated: "25 min ago",
  },
];